[package]
name = "hashsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
crossbeam-channel = "0.5.8"
num_cpus = "1.16.0"
sha2 = "0.10.7"
